# Generated by Django 3.0.8 on 2020-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
