# Generated by Django 3.0.8 on 2020-08-29 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0005_auto_20200821_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(related_name='adz_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
