# Generated by Django 3.0.8 on 2020-09-04 16:28

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=osm_field.fields.OSMField(default=2, lat_field='location_lat', lon_field='location_lon'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_lat',
            field=osm_field.fields.LatitudeField(default=2, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_lon',
            field=osm_field.fields.LongitudeField(default=2, validators=[osm_field.validators.validate_longitude]),
        ),
    ]
