# Generated by Django 3.0.8 on 2020-09-04 16:38

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200904_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location_lat',
            field=osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location_lon',
            field=osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude]),
        ),
    ]
