# Generated by Django 3.0.8 on 2020-09-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200904_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_above',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_basement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_living',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_living15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_lot15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='waterfront',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='yr_built',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='yr_renovated',
            field=models.IntegerField(default=0),
        ),
    ]
