# Generated by Django 3.0.8 on 2020-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200913_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft_above',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft_basement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft_living',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft_living15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft_lot15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='view',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='waterfront',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='yr_built',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='yr_renovated',
            field=models.IntegerField(),
        ),
    ]
