# Generated by Django 3.0.8 on 2020-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='maximum_loan_amount',
            field=models.IntegerField(default=0),
        ),
    ]
