# Generated by Django 3.0.8 on 2020-08-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200820_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
