# Generated by Django 3.0.8 on 2020-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mortgage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
