# Generated by Django 3.0.8 on 2020-08-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_mortgage_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='contact_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
