# Generated by Django 3.0.8 on 2020-08-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200821_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
