# Generated by Django 3.0.8 on 2020-08-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200821_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal',
            old_name='maximum_loan_amount',
            new_name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='interest_rate',
        ),
    ]
