# Generated by Django 3.0.8 on 2020-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200821_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
