# Generated by Django 3.0.8 on 2020-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_mortgage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
