# Generated by Django 3.0.8 on 2020-09-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_builder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='service_in_breif',
            new_name='service_in_brief',
        ),
    ]
