# Generated by Django 3.0.8 on 2020-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200830_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media\\photos\x820\x008\x18\x07rab-man-portrait-260nw-409360072_7p7pGVB.webp', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
