# Generated by Django 3.0.8 on 2020-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200830_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media\\photos\x820\x008\x18\\images.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
